const PROJECT_DIR = '/home/parallels/Desktop/ai-runtime-security-framework-desktop';
const PYTHON = `${PROJECT_DIR}/venv/bin/python`;
const STREAMLIT = `${PROJECT_DIR}/venv/bin/streamlit`;

module.exports = {
  apps: [
    {
      name: 'airs-gateway',
      interpreter: PYTHON,
      script: 'gateway/app.py',
      cwd: PROJECT_DIR,
      env: {
        PYTHONPATH: PROJECT_DIR,
        GATEWAY_HOST: '0.0.0.0',
        GATEWAY_PORT: '8000',
        LOG_LEVEL: 'INFO',
        AUDIT_LOG_FILE: `${PROJECT_DIR}/logs/audit.log`,
      },
      log_file: `${PROJECT_DIR}/logs/pm2-gateway.log`,
      error_file: `${PROJECT_DIR}/logs/pm2-gateway-error.log`,
      out_file: `${PROJECT_DIR}/logs/pm2-gateway-out.log`,
      time: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      watch: false,
    },
    {
      name: 'airs-content-mod',
      interpreter: PYTHON,
      script: 'services/content_moderation/app_a_content.py',
      cwd: PROJECT_DIR,
      env: {
        PYTHONPATH: `${PROJECT_DIR}:${PROJECT_DIR}/services`,
        SERVICE_PORT: '8001',
      },
      log_file: `${PROJECT_DIR}/logs/pm2-content-mod.log`,
      error_file: `${PROJECT_DIR}/logs/pm2-content-mod-error.log`,
      out_file: `${PROJECT_DIR}/logs/pm2-content-mod-out.log`,
      time: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      watch: false,
    },
    {
      name: 'airs-finance',
      interpreter: PYTHON,
      script: 'services/finance_analysis/app_b_finance.py',
      cwd: PROJECT_DIR,
      env: {
        PYTHONPATH: `${PROJECT_DIR}:${PROJECT_DIR}/services`,
        SERVICE_PORT: '8002',
      },
      log_file: `${PROJECT_DIR}/logs/pm2-finance.log`,
      error_file: `${PROJECT_DIR}/logs/pm2-finance-error.log`,
      out_file: `${PROJECT_DIR}/logs/pm2-finance-out.log`,
      time: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      watch: false,
    },
    {
      name: 'airs-support',
      interpreter: PYTHON,
      script: 'services/support_chatbot/app_c_support.py',
      cwd: PROJECT_DIR,
      env: {
        PYTHONPATH: `${PROJECT_DIR}:${PROJECT_DIR}/services`,
        SERVICE_PORT: '8003',
      },
      log_file: `${PROJECT_DIR}/logs/pm2-support.log`,
      error_file: `${PROJECT_DIR}/logs/pm2-support-error.log`,
      out_file: `${PROJECT_DIR}/logs/pm2-support-out.log`,
      time: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      watch: false,
    },
    {
      name: 'airs-dashboard',
      interpreter: PYTHON,
      script: 'master_dashboard/app.py',
      cwd: PROJECT_DIR,
      env: {
        PYTHONPATH: PROJECT_DIR,
        DASHBOARD_PORT: '9000',
        AUDIT_LOG_FILE: `${PROJECT_DIR}/logs/audit.log`,
        AUDIT_LOG_JSONL: '/tmp/airs_audit/audit.jsonl',
      },
      log_file: `${PROJECT_DIR}/logs/pm2-dashboard.log`,
      error_file: `${PROJECT_DIR}/logs/pm2-dashboard-error.log`,
      out_file: `${PROJECT_DIR}/logs/pm2-dashboard-out.log`,
      time: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      watch: false,
    },
    {
      name: 'airs-streamlit',
      interpreter: 'bash',
      script: '-c',
      args: `${STREAMLIT} run dashboard/streamlit_app.py --server.port 8501 --server.headless true --server.address 0.0.0.0`,
      cwd: PROJECT_DIR,
      env: {
        PYTHONPATH: PROJECT_DIR,
      },
      log_file: `${PROJECT_DIR}/logs/pm2-streamlit.log`,
      error_file: `${PROJECT_DIR}/logs/pm2-streamlit-error.log`,
      out_file: `${PROJECT_DIR}/logs/pm2-streamlit-out.log`,
      time: true,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 3000,
      watch: false,
    },
  ],
};
